import AppKit
import CryptoKit

/// R58: what was copied last, offered once as the note of a task typed in quick entry.
enum ClipboardNote {
    /// A longer text is left alone: it is not cut to fit.
    static let limit = 2000
    private static let usedKey = "clipboardNoteUsed"
    /// Marks that password managers and the like put on what is not to be kept (nspasteboard.org).
    private static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
    ]

    static var pasteboard: NSPasteboard {
        #if DEBUG
        // A check fills a pasteboard of its own, not the one the person at the machine copies to.
        if let name = ProcessInfo.processInfo.environment["LISTS_DEBUG_PASTEBOARD"] { return NSPasteboard(name: .init(name)) }
        #endif
        return .general
    }

    /// The text to start the note with, or nil when there is none or it was offered before.
    static func take(from pasteboard: NSPasteboard = ClipboardNote.pasteboard, defaults: UserDefaults = .standard) -> String? {
        guard let types = pasteboard.types, !types.contains(.fileURL),
              !types.contains(where: { concealed.contains($0.rawValue) }) else { return nil }
        let copied = pasteboard.string(forType: .string) ?? pasteboard.string(forType: .URL)
        guard let text = copied?.trimmingCharacters(in: .whitespacesAndNewlines), !text.isEmpty, text.count <= limit else { return nil }
        // The change count starts over with the login session, so the text is told apart as well.
        let digest = SHA256.hash(data: Data(text.utf8)).map { String(format: "%02x", $0) }.joined()
        let mark = "\(pasteboard.changeCount) \(digest)"
        guard defaults.string(forKey: usedKey) != mark else { return nil }
        defaults.set(mark, forKey: usedKey)
        return text
    }
}
